# Generated by Django 4.0.4 on 2023-06-01 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanghoa',
            name='ten_hang_hoa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên hàng hoá'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='file_hop_dong',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File hợp đồng'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ma_ncc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_core.ncc', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_het_han',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='ngay_hieu_luc',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hiệu lực'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='phu_luc_hop_dong',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='Phụ lục hợp đồng'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đã duyệt', 'Đã duyệt'), ('Đang có hiệu lực', 'Đang có hiệu lực'), ('Đã hết hạn', 'Đã hết hạn')], default='Đang xem xét', max_length=100, null=True, verbose_name='Trạng thái hợp đồng'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='cong_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Công nợ'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='file_bao_gia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File báo giá'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='giay_phep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giấy phép'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='nang_luc_hang_hoa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Năng lực hàng hoá'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='nguoi_lien_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='sdt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='stk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thông tin chuyển khoản'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='ten_doanh_nghiep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên doanh nghiệp'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(blank=True, choices=[('Quản lí', 'Quản lí'), ('Nhân viên', 'Nhân viên')], max_length=50, null=True, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='phong_ban',
            field=models.CharField(blank=True, choices=[('Thu mua', 'Thu mua'), ('Kho', 'Kho'), ('Kế toán', 'Kế toán'), ('Khác', 'Khác')], max_length=50, null=True, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='po',
            name='ma_nhan_vien_tao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nv_tao_PO', to='web_core.nhanvien', verbose_name='Mã nhân viên tạo'),
        ),
        migrations.AlterField(
            model_name='po',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã nhận hàng', 'Đã nhận hàng'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phê duyệt', max_length=100, null=True, verbose_name='Trạng thái PO'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phân công', max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='pr_hh',
            name='ma_hang_hoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_core.hanghoa', verbose_name='Mã hàng hoá'),
        ),
        migrations.AlterField(
            model_name='pr_hh',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phân công', max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='so_tien',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền đã thanh toán'),
        ),
    ]
