# Generated by Django 4.0.4 on 2023-05-13 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncc',
            name='cong_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Công nợ'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='file_bao_gia',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File báo giá'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='giay_phep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giấy phép'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='nang_luc_hang_hoa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Năng lực hàng hoá'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='nguoi_lien_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Người liên hệ'),
        ),
        migrations.AlterField(
            model_name='ncc',
            name='stk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thông tin chuyển khoản'),
        ),
        migrations.AlterField(
            model_name='po',
            name='trang_thai',
            field=models.CharField(blank=True, choices=[('Chờ phê duyệt', 'Chờ phê duyệt'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã nhận hàng', 'Đã nhận hàng'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phê duyệt', max_length=100, null=True, verbose_name='Trạng thái PO'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phân công', max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='pr_hh',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ phân công', 'Chờ phân công'), ('Đang thực hiện', 'Đang thực hiện'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ phân công', max_length=100, null=True, verbose_name='Trạng thái PR'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='so_tien',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền đã thanh toán'),
        ),
    ]
