# Generated by Django 4.0.4 on 2023-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0003_alter_hopdong_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='phong_ban',
            field=models.CharField(blank=True, choices=[('Thu mua', 'Thu mua'), ('Kho', 'Kho'), ('Kế toán', 'Kế toán'), ('R&D', 'R&D'), ('Production', 'Production'), ('Khác', 'Khác')], max_length=50, null=True, verbose_name='Phòng ban'),
        ),
    ]
